spring.application.name=tambuto
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/myrealm
# Sostituisci "tambuto-client" con il nome esatto del Client che creerai dentro Keycloak
jwt.auth.converter.resource-id=tambuto-client

jwt.auth.converter.principle-attribute=preferred_username

